//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWhoAmI
    {
        public int WhoAmIID { get; set; }
        public string Title1 { get; set; }
        public string Description { get; set; }
        public string Title2 { get; set; }
        public string CvURL { get; set; }
    }
}
